import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ModeToggle } from "@/components/mode-toogle";
import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider, User } from "@/components/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const user: User = {
    id: "30312020212337",
    name: "Ali Magdy",
    email: "alimagdy1234321@gmail.com",
    avatar: "/images/Capture.PNG",
    role: "Admin",
    affiliation: "University",
    country: "Egypt",
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex items-start justify-between`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UserProvider initialUser={user}>
            <SidebarProvider>
              <AppSidebar />
              <main>
                <SidebarTrigger />
                <ModeToggle />
                {children}
              </main>
            </SidebarProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}